import { useAuth } from '../hooks/useAuth';
import { authService } from '../services/authService';
import dashboardLogo from '../../../img/logo2.webp';
import { BarChart3, ChevronDown, ClipboardList, LogOut, Menu, Pencil, UserRound, UsersRound } from 'lucide-react';

const orders = [
  ['0297317820', 'CAMBIO', '22/07/2026 08:00', 'INGRESADO', '22/07/2026', '—'],
  ['0297317819', 'GAS', '22/07/2026 07:58', 'INGRESADO', '22/07/2026', '—'],
  ['0297317818', 'CAMBIO', '21/07/2026 16:24', 'ATENDIDO', '22/07/2026', '001-45872']
];

export function DashboardPage() { const { partner, loading } = useAuth(); if (loading) return <main className="dashboard"><p>Cargando…</p></main>; if (!partner) { window.location.href = '/login'; return null; } const logout = async () => { await authService.logout(); window.location.href = '/login'; }; return <main className="dashboard"><header className="dashboard-topbar"><div className="topbar-brand"><img src={dashboardLogo} alt="Logo"/></div><div className="topbar-welcome">HOLA, SOCIO ESTRATÉGICO</div><nav className="topbar-nav"><a href="#negocios">NEGOCIOS Y TRANSPORTES</a><span className="topbar-divider"/><span>Código <strong>{partner.ruc}</strong></span><button onClick={logout}>Cerrar sesión</button><button className="profile-menu"><Menu size={18}/> MI PERFIL <ChevronDown size={15}/></button></nav></header><div className="dashboard-body"><section className="dashboard-content"><button className="change-order"><span className="change-icon"><ClipboardList size={32}/></span><strong>HAZ TU PEDIDO DE CAMBIO</strong></button><div className="content-heading"><BarChart3 size={22}/><h1>Estado de pedidos últimos 30 días</h1></div><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>NRO PEDIDO</th><th>TIPO</th><th>FECHA<br/>PEDIDO</th><th>ESTADO DEL<br/>PEDIDO</th><th>FECHA<br/>PROGRAMACIÓN</th><th>NRO<br/>FACTURA</th></tr></thead><tbody>{orders.map(order => <tr key={order[0]}>{order.map((value,index) => <td key={index}>{value}</td>)}</tr>)}</tbody></table></div></section><aside className="dashboard-sidebar"><section className="sidebar-section"><div className="sidebar-title"><UserRound size={20}/> <span>PERFIL COMERCIAL</span></div><div className="profile-avatar"><UserRound size={50}/></div><button className="orange-button"><Pencil size={14}/> EDITAR</button><p className="business-name">{partner.businessName}</p></section><section className="sidebar-section admins"><div className="sidebar-title"><UsersRound size={20}/> <span>ADMINISTRADORES</span></div><p>No se han definido<br/>administradores</p><button className="orange-button">CREAR NUEVO USUARIO</button></section></aside></div></main>; }
