import { useAuth } from '../hooks/useAuth';
import { authService } from '../services/authService';
import logo2 from '../../../img/logo2.webp';
import banner from '../../../img/banner_mis_pedidos.png';
import profileImage from '../../../img/sinfoto.jpg';
import cylinderImage from '../../../img/balon.png';
import { ChevronDown, GraduationCap, LayoutGrid, LogOut, MessageSquare, ShoppingCart, Truck, UserRound, Calculator, FileText } from 'lucide-react';

const menu = [['INICIO', LayoutGrid], ['MIS PEDIDOS', ShoppingCart], ['MI NEGOCIO', Calculator], ['ACADEMIA SOLGAS', GraduationCap], ['APP REPARTIDOR', Truck], ['MI ASISTENTE', MessageSquare], ['POPUPS', LayoutGrid], ['MI TIENDA', ShoppingCart], ['WEB DIST', LayoutGrid], ['CAMBIAR INSTALACIÓN', UserRound]] as const;
const masgasOrders = [['0297324548', 'GAS', '11/08/2026 16:20', 'DESPACHADO', '12/08/2026', '0106519274'], ['0297323799', 'GAS', '09/08/2026 14:54', 'ENTREGADO', '10/08/2026', '0106518572'], ['0297322608', 'CAMBIO', '05/08/2026 17:02', 'INGRESADO', '06/08/2026', ''], ['0297322605', 'GAS', '05/08/2026 17:00', 'ENTREGADO', '06/08/2026', '0106517578'], ['0297321510', 'GAS', '02/08/2026 16:14', 'ENTREGADO', '03/08/2026', '0106516623'], ['0297320980', 'CAMBIO', '31/07/2026 15:29', 'INGRESADO', '01/08/2026', ''], ['0297320978', 'GAS', '31/07/2026 15:27', 'ENTREGADO', '01/08/2026', '0106516282'], ['0297319302', 'GAS', '26/07/2026 14:33', 'ENTREGADO', '27/07/2026', '0106514646'], ['0297318261', 'GAS', '23/07/2026 11:40', 'ENTREGADO', '23/07/2026', '0106513694'], ['0297317820', 'CAMBIO', '22/07/2026 08:00', 'INGRESADO', '22/07/2026', ''], ['0297317819', 'GAS', '22/07/2026 07:58', 'ENTREGADO', '22/07/2026', '0106513198'], ['0297317119', 'GAS', '20/07/2026 16:06', 'ENTREGADO', '21/07/2026', '0106512842'], ['0297315895', 'GAS', '16/07/2026 15:21', 'ENTREGADO', '17/07/2026', '0106511817'], ['0297315530', 'GAS', '15/07/2026 15:36', 'ENTREGADO', '16/07/2026', '0106511468']];

export function OrdersPage() {
  const { partner, loading } = useAuth();
  if (loading) return <main className="orders-page"><p>Cargando…</p></main>;
  if (!partner) { window.location.href = '/login'; return null; }
  const installation = (() => { try { return JSON.parse(sessionStorage.getItem('selectedInstallation') ?? localStorage.getItem('selectedInstallation') ?? 'null') as { code?: string; brand?: string } | null; } catch { return null; } })();
  const displayCode = installation?.code || partner.ruc;
  const isMasgas = displayCode === '62173920' || installation?.brand === 'MASGAS';
  const logout = async () => { await authService.logout(); window.location.href = '/login'; };
  const go = (label: string) => { if (label === 'INICIO') window.location.href = '/dashboard'; if (label === 'MI NEGOCIO') window.location.href = '/business'; if (label === 'CAMBIAR INSTALACIÓN') window.location.href = '/select-installation'; if (label === 'MI PERFIL') window.location.href = '/profile'; if (label === 'MI ASISTENTE') window.location.href = '/assistant'; };
  return <main className="orders-page"><header className="portal-topbar"><div className="portal-logo"><img src={logo2} alt="Logo empresarial"/></div><div className="portal-greeting">HOLA, SOCIO ESTRATÉGICO</div><button className="portal-avatar" onClick={() => go('MI PERFIL')} aria-label="Abrir mi perfil"><img src={profileImage} alt="Perfil del socio"/></button><div className="portal-account"><span>NEGOCIOS Y TRANSPORTES PIZAN EIRL</span><i/><span>Código <strong>{displayCode} {isMasgas ? 'MASGAS' : 'SOLGAS'}</strong></span><button onClick={logout}><LogOut size={14}/> Cerrar sesión</button><button className="portal-profile" onClick={() => go('MI PERFIL')}><UserRound size={16}/> MI PERFIL <ChevronDown size={14}/></button></div></header><div className="orders-banner" style={{ backgroundImage: `url(${banner})` }}/><nav className="portal-menu orders-menu">{menu.map(([label, Icon]) => <button key={label} className={label === 'MIS PEDIDOS' ? 'active' : ''} onClick={() => go(label)}><Icon size={19}/><span>{label}</span></button>)}</nav><section className="orders-content"><div className="orders-breadcrumb">HOME <b>›</b> MIS PEDIDOS</div><h1><img className="orders-cylinder-title" src={cylinderImage} alt=""/> Mis pedidos</h1><p className="orders-subtitle">Presiona aquí y haz tu pedido de gas o cambio en <strong>simples pasos</strong></p><div className="order-actions"><button onClick={() => { window.location.href = '/orders/gas'; }}><span><img src={cylinderImage} alt=""/></span> HAZ TU PEDIDO DE GAS</button><button onClick={() => { window.location.href = '/orders/gas'; }}><span><img src={cylinderImage} alt=""/></span> HAZ TU PEDIDO DE CAMBIO</button></div><h2>Estado de pedidos últimos 30 días</h2>{isMasgas ? <table className="orders-table"><thead><tr><th>NRO PEDIDO</th><th>TIPO</th><th>FECHA PEDIDO</th><th>ESTADO DEL PEDIDO</th><th>FECHA PROGRAMACIÓN</th><th>NRO FACTURA</th><th>OPCIONES</th></tr></thead><tbody>{masgasOrders.map(order => <tr key={order[0]}>{order.map((value, index) => <td key={index}>{value}</td>)}<td><button className="order-file" aria-label="Ver documento"><FileText size={16}/></button></td></tr>)}</tbody></table> : <p className="orders-empty">No tienes pedidos en los últimos 30 días.</p>}<button className="orders-history">VER ÚLTIMOS 12 MESES <b>⊕</b></button><p className="orders-reference"><em>Referencia al estado del pedido:</em><br/><strong>BLOQUEADO:</strong> Pedido a la espera de liberación / <strong>INGRESADO:</strong> Pedido registrado en sistema / <strong>DESPACHADO:</strong> Pedido ya está en ruta / <strong>ENTREGADO:</strong> Pedido y factura recibida</p></section><footer className="orders-footer"><nav><a>INICIO</a><a>MIS PEDIDOS</a><a>MI NEGOCIO</a><a>ACADEMIA SOLGAS</a><a>APP REPARTIDOR</a><a>MI ASISTENTE</a><a>POPUPS</a><a>MI TIENDA</a></nav><div>AYUDA <span>|</span> CONTACTO</div></footer></main>;
}
