using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Text;
using PartnerPortal.Api.Domain;
namespace PartnerPortal.Api.Infrastructure;
public interface IPartnerRepository { Partner? FindByRuc(string ruc); void Save(Partner partner); }
public sealed class InMemoryPartnerRepository : IPartnerRepository { private readonly ConcurrentDictionary<string,Partner> data = new(); public Partner? FindByRuc(string ruc) => data.TryGetValue(ruc, out var p) ? p : null; public Partner? FindById(Guid id) => data.Values.FirstOrDefault(x => x.Id == id); public void Save(Partner partner) => data[partner.Ruc] = partner; }
public sealed record CaptchaEntry(string Hash, DateTime ExpiresAt, bool Used);
public interface ICaptchaStore { void Put(string id, string answer, DateTime expiresAt); bool Consume(string id, string answer); }
public sealed class InMemoryCaptchaStore : ICaptchaStore { private readonly ConcurrentDictionary<string,CaptchaEntry> data = new(); public void Put(string id,string answer,DateTime expiresAt) => data[id] = new(Hash(answer),expiresAt,false); public bool Consume(string id,string answer) { if(!data.TryGetValue(id,out var e) || e.Used || e.ExpiresAt < DateTime.UtcNow) return false; data[id] = e with { Used=true }; return CryptographicOperations.FixedTimeEquals(Convert.FromHexString(e.Hash), Convert.FromHexString(Hash(answer))); } private static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))); }
public sealed class SessionStore { public sealed record Session(Guid PartnerId, DateTime AccessExpires, DateTime RefreshExpires, string RefreshHash); private readonly ConcurrentDictionary<string,Session> sessions = new(); public void Add(string token, Session s) => sessions[token]=s; public bool TryGet(string token,out Session? session) { if(sessions.TryGetValue(token,out var s) && s.AccessExpires > DateTime.UtcNow){session=s;return true;} session=null;return false;} public bool TryGetByRefresh(string refreshHash,out string? accessToken,out Session? session) { var match=sessions.FirstOrDefault(x => x.Value.RefreshHash == refreshHash && x.Value.RefreshExpires > DateTime.UtcNow); if(match.Key is not null){accessToken=match.Key;session=match.Value;return true;} accessToken=null;session=null;return false; } public void Remove(string token) => sessions.TryRemove(token,out _); }
public sealed class LoginAuditStore { public ConcurrentQueue<LoginAudit> Items { get; } = new(); public void Add(LoginAudit item) => Items.Enqueue(item); }
public sealed class LoginRateLimiter { private readonly ConcurrentDictionary<string,(int Count,DateTime Reset)> attempts = new(); public bool Allowed(string key) { var now=DateTime.UtcNow; var item=attempts.GetOrAdd(key, _ => (0,now.AddMinutes(5))); if(item.Reset <= now) { attempts[key]=(0,now.AddMinutes(5)); return true; } return item.Count < 5; } public void Failed(string key) { var item=attempts.GetOrAdd(key, _ => (0,DateTime.UtcNow.AddMinutes(5))); attempts[key]=(item.Count+1,item.Reset); } }
